<?php
# This file was automatically generated by the MediaWiki 1.20.4
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "WikiQPool";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://pool.wikiq.org";

## Database settings
$wgDBname           = "wiki_pool";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";



# Shared configuration
require_once( "$IP/config/PrivateSettings.php" );
require_once( "$IP/config/WikiFamilySettings.php" );
require_once( "$IP/config/ExtensionSettings.php" );


# End of automatically generated settings.
# Add more configuration options below.

