<?php
# This file was automatically generated by the MediaWiki 1.20.4
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

require_once( "$IP/config/WikiSubdomains.php" );

$wikiconf = NULL;
$wikiname = NULL;
if ( isset($_SERVER["SERVER_NAME"]) && preg_match( '/^(.*)\.wikiq.org$/', $_SERVER["SERVER_NAME"], $matches ) ) {
	 $wikiname = strtolower($matches[1]);
	 $wikiconf = $wikiSubdomains[$wikiname];
} else {	
	$dbname = '';
	# The --wiki param must the second argument to to avoid
	# any "options with args" ambiguity (see Maintenance.php).
	if ( isset( $argv[1] ) && $argv[1] === '--wiki' ) {
		$dbname = isset( $argv[2] ) ? $argv[2] : ''; // "script.php --wiki dbname"
	} elseif ( isset( $argv[1] ) && substr( $argv[1], 0, 7 ) === '--wiki=' ) {
		$dbname = substr( $argv[1], 7 ); // "script.php --wiki=dbname"
	} elseif ( isset( $argv[1] ) && substr( $argv[1], 0, 2 ) !== '--' ) {
		$dbname = $argv[1]; // "script.php dbname"
	}
	if ($dbname !== '') {	
		foreach ($wikiSubdomains as $wSubName => $wSubValue) {
			if ($wSubValue["db"] === $dbname) {
				$wikiname = $wSubName;
				$wikiconf = $wSubValue;
				break;
			}
		}
	}
}


if (isset($wikiconf)) {
	# Site name
	$wgSitename = $wikiconf["sitename"];
	# The protocol and server name to use in fully-qualified URLs
	$wgServer = $wikiconf["server"];
	# Database name
	$wgDBname = $wikiconf["db"];
	# Site language code, should be one of the list in ./languages/Names.php
	$wgLanguageCode = $wikiconf["language"];
} else {
	header('Location: http://wikiq.org');
	echo "No database information";
	exit();
    //die( "Invalid host name, can't determine wiki name" );
    // You could also redirect to a nicer "No such wiki" page.
}

# Shared configuration
require_once( "$IP/config/PrivateSettings.php" );
require_once( "$IP/config/WikiFamilySettings.php" );
require_once( "$IP/config/ExtensionSettings.php" );


# End of automatically generated settings.
# Add more configuration options below.

