#!/bin/bash

source ./config.inc

for dbname in wiki_pool wiki_en wiki_ua wiki_ru
do
  dumps="$base/dumps"
  [ -e $dumps ]  || mkdir $dumps
  dumpfile="$dumps/dump-$dbname.xml"
  timestamp=`date -u +%Y-%m-%d`
  slave=`php $mediawiki/maintenance/getSlaveServer.php \
    --wiki $dbname \
    --conf $mediawiki/LocalSettings.php \
    --aconf $mediawiki/AdminSettings.php`
  echo "Dumping $dbname..."
  cd $mediawiki && php maintenance/dumpBackup.php \
    --wiki $dbname \
    --conf $mediawiki/LocalSettings.php \
    --aconf $mediawiki/AdminSettings.php \
    --current \
    --server=$slave > $dumpfile
  [ -e $indexes/status ] || mkdir -p $indexes/status
  echo "timestamp=$timestamp" > $indexes/status/$dbname

  cd $base &&
  java -cp LuceneSearch.jar org.wikimedia.lsearch.importer.BuildAll $dumpfile $dbname
done